fix cert manager timeout
cnoe-io/reference-implementation-aws pull request #44
Opened 2024-08-30 18:25 UTC by zjaco13

Adds a null resource to cert manager to stop the timeout when creating

2024-08-30 18:30 UTC, elamaran11 commented
@nimakaviani Please approve this. This is another bug we found while using reference-implementation.

2024-09-05 21:20 UTC, nabuskey requested changes
Thanks for this! Just a minor comment to make sure we aren't using something that's deprecated.

2024-09-05 21:20 UTC, nabuskey commented on terraform/cert-manager.tf
> +resource "null_resource" "wait_for_cert_manager" {
null_resource is deprecated. let's use what's suggested in the doc here: https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource

2024-09-06 19:27 UTC, nabuskey reviewed
Thanks for making the change. Just have a question about the new module being added. Please also fix DCO so we can merge: https://github.com/apps/dco

2024-09-06 19:27 UTC, nabuskey commented on terraform/versions.tf
> +    }
Is this module needed?

2024-09-06 23:22 UTC, nabuskey approved these changes
LGTM. Thank you very much.

2024-09-06 23:22 UTC, merged